export let listOfParties = [
  {name:'SMER',
  number: 0,
  hlasy: 49},
  {name: 'SaS',
  number: 1,
  hlasy: 21},
  {name: 'OĽaNO-Nova',
  number: 2,
  hlasy: 19},
  {name: 'SNS',
  number: 3,
  hlasy: 15},
  {name: 'Kotleba',
  number: 4,
  hlasy: 14},
  {name: 'Sme Rodina',
  number: 5,
  hlasy: 11},
  {name: 'MOST-HÍD',
  number: 6,
  hlasy: 11},
  {name: '#Sieť',
  number: 7,
  hlasy: 10}
]
